### ISSUE TITLE
Layout blinking

### ISSUE THREAD

**Issue by pavelpashkovsky** [paulcollett/react-masonry-css#21]
I recorded a small video about this issue. 

https://monosnap.com/file/7Mt9QHv2Y85ht5kO0L3MP83YpjAglA#embed

This component shows 2 cols during loading. But then it switching to right @media section.

**Comment by pavelpashkovsky** [comment]
any updates?

**Comment by brxck** [comment]
I'm having the same issue. This is because of the [number of columns is always 2](https://github.com/paulcollett/react-masonry-css/blob/e080b5e7672011a5ce14b3e034868d6f2f051091/src/react-masonry-css.js#L12) at the initial render. I think it would make sense if the `default` value from breakpointCols was loaded into state for the first render.

**Comment by paulcollett** [comment]
Resolved in #25
