### ISSUE TITLE
Enforcing minimum or fixed widths for children?

### ISSUE THREAD

**Issue by oyeanuj** [paulcollett/react-masonry-css#22]
Hi @paulcollett! Thank you for creating this library! I was trying to use it to render post embeds all of which are a fixed width (and while can expand with margin, they can't go below a certain width).

On using this library as recommended, I notice:

<img width="1187" alt="screen shot 2018-10-21 at 9 40 08 am" src="https://user-images.githubusercontent.com/9633371/47269647-b0151000-d515-11e8-85f9-55bf2cba2443.png">

Here is my code:
```jsx
const breakpointColumnsObj = {
	"default": 2,
	1600: 4,
	1200: 3,
	800: 2,
	400: 1,
}

return (
	<Masonry
		breakpointCols = { breakpointColumnsObj }
		className = "post-preview-grid"
		columnClassName = "post-preview-column"
	>
		{ this.renderPosts() }
	</Masonry>
)
```

I'm not sure if this is possible and I'm misunderstanding breakpoints in this case or is there some other tweak that I need?

Thank you!

**Comment by paulcollett** [comment]
@oyeanuj, because each of your items are a set pixel width you'll also need to specify a set width for the masonary component. To do this, you'll want to have a parent element around the masonry component to set the width you need at all the different breakpoints.

```
<div style="width: 800px">
<Masonry ...>...</Masonry>
</div>
```

A common approach I take is to size each of the elements inside of masonry, in this case your posts, to be 100% width along with all elements inside of it (like images). That way whatever the size of the column your posts will fit it nicely
