### ISSUE TITLE
Left-to-right content flow

### ISSUE THREAD

**Issue by filipjnc** [paulcollett/react-masonry-css#35]
It would be great to have an option to set content to flow from left to right instead of top to bottom.

A possible solution would be to reorder the passed array of React elements like described [here](https://hackernoon.com/masonry-layout-technique-react-demo-of-100-css-control-of-the-view-e4190fa4296) before rendering.

![image](https://user-images.githubusercontent.com/16118391/60965981-84da8700-a317-11e9-9fd9-ff0add604c7d.png)

**Comment by paulcollett** [comment]
You've found the right plugin then! *left to right flow is exactly how this plugin works* regardless of what props you pass

**Comment by filipjnc** [comment]
@paulcollett yes and no. The content is indeed flowing from left to right but it's rendered in the dom from top to bottom. Keyboard navigation for people with disabilities is a pain.

Is there a way to also render them in the dom left to right or does the focus need to be hacked to behave in this way?

**Comment by MichalMoravik** [comment]
@filipjnc Hey! This is exactly now my problem since it only counts a total number of objects and then dividing it. I am working with photos and something one of my photo is bigger than 2 other photos. This is then problem and it arranges them in one row. 

@filipjnc Did you find some other solution for this library? Could you send me the link if yes, please? I am in the urgent mode and this can make me much slower. :/ Thanks!
