### ISSUE TITLE
Wrong column width when items count < max columns

### ISSUE THREAD

**Issue by b0000ring** [paulcollett/react-masonry-css#57]
Hello!
First of all, thank you for the awesome library. It's really helpful.
I found a strange behaviour when items count is less than max columns.
For example, if I have 4 columns by default and only 2 items, it renders only 2 columns.
The problem is - the width of that columns sets as 25% which is 25% from grid with only two columns, not 25% from grid of 4 columns!
In a case when I know max width of grid it's ok, but when I don't know it, I get my items too tiny by their width.
Is it possible to render all 4 columns in case I have only 2 items, or set 50% column width for 2 columns in this case?
Thank you!

**Comment by tayloraucoin** [comment]
I'm experiencing this too in a slightly different way.  I run a filter operation on my content, where I dynamically change my data.length to sometimes less than the total columns set. 

Adding a conditional to validate that the minimum amount of data items is less than the columns before setting the width % would be great!

To echo the previous statement, great library!  And very lightweight which is appreciated :)

**Comment by tayloraucoin** [comment]
Here is a work-around for anyone else who encounters this:

```
import styled from "styled-components";

const breakpointColumnsObj {
  default: 4,
  1800: 3,
  1400: 2,
  875: 1
};

const breakpointColumnsObjKeys = Object.keys(breakpointColumnsObj);

const Root = styled.div`
  ...
    
  .my-masonry-grid_column {
    ...
    width: ${props => props.dataLength === 3 && "33.3333% !important"};
    width: ${props => props.dataLength === 2 && "50% !important"};
    width: ${props => props.dataLength === 1 && "100% !important"};
  }

  @media screen and (max-width: ${breakpointColumnsObjKeys[2]}px) {
    .my-masonry-grid_column {
      width: ${props => props.dataLength === 2 && "50% !important"};
      width: ${props => props.dataLength === 1 && "100% !important"};
    }
  }

  @media screen and (max-width: ${breakpointColumnsObjKeys[1]}px) {
    .my-masonry-grid_column {
      width: ${props => props.dataLength === 1 && "100% !important"};
    }
  }
`;

```

**Comment by paulcollett** [comment]
I think we should look into this as it's both a bug and a feature for a few people. Which means maybe we look at it being an option of:
a) span items all the way across when items < column count (current behavior)
b) always be the specified column count (new behavior)

From the sounds of it, and I personally feel like `b` is the expected behavior and should be the default even if we were to make this an option.

**Comment by b0000ring** [comment]
Yes, I think the possibility to choose behaviour is a best option, if it's possible to implement!
Thank you!

**Comment by jsgao0** [comment]
Instead of specified column count, I recommend that it keep the columns from the current behavior, and then we could center the items if the its count is less than calculated columns for current breakpoint. For example, if the calculated columns is 4 and there are 2 items then the first item and 2nd item will be painted in 2nd column and 3rd column, i.e., the first column and the last column are empty. Like this:

| empty | item1 | item2 | empty |

equivalent HTML code snippet

```
<ul>
  <li class="column"></li>
  <li class="column">item1</li>
  <li class="column">item2</li>
  <li class="column"></li>
</ul>
```
